#!/bin/bash

SETUID=33
AUTOTEST_ROOT=$(dirname "$0")
AUTOTEST_ROOT=$(cd "$AUTOTEST_ROOT" && pwd -P)
AUTOTEST_RUN="uBasic uSimple uComplet iComplet"
PATH="$AUTOTEST_ROOT/bin:$PATH"

export AUTOTEST_ROOT
export AUTOTEST_RUN
export PATH

if [ -f "$AUTOTEST_ROOT/autotest.conf" ]; then
	. "$AUTOTEST_ROOT/autotest.conf"
fi

if [ "$(id -u)" != "${SETUID}" ]; then
	printf "Script must be run under UID '%s'.\n" "${SETUID}"
	exit 1
fi

if [ ! -d "${AUTOTEST_ROOT}/logs" ]; then
	mkdir -p "${AUTOTEST_ROOT}/logs"
fi

echo $$ >> "${AUTOTEST_ROOT}/autotest.lock"
LOCK_PID=$(head -1 "${AUTOTEST_ROOT}/autotest.lock")
if [ "${LOCK_PID}" != "$$" ]; then
	printf "Process already running with PID '%s'.\n" "${LOCK_PID}"
	exit 2
fi

function on_exit {
	rm "${AUTOTEST_ROOT}/autotest.lock"
}

trap on_exit EXIT

function timestamplog {
	perl -MPOSIX -ne 'BEGIN{select STDOUT;$|=1;$ts=time()}printf("%s +%s %s",strftime("%Y-%m-%dT%H:%M:%S",localtime()),time()-$ts,$_);'
}

REDIR="/dev/stdout"
if [ ! -t 0 ]; then
	REDIR="/dev/null"
fi

function install_control {
	mkdir -p "${AUTOTEST_ROOT}/dynacase-control"
	wget -O - http://eec.corp.anakeen.com/anakeen/repo/integration/3.2/tarball/dynacase-control-current.tar.gz | tar -C "${AUTOTEST_ROOT}/dynacase-control" -zxf - --strip-components 1
}

function autotest_run {
	while [ $# -gt 0 ]; do
		SCRIPT=$(echo "$1" | sed -e 's:/:_:g')
		TS=$(date +%Y-%m-%dT%H:%M:%S)
		OUTPUT="${AUTOTEST_ROOT}/logs/${SCRIPT}_${TS}.log"

		(
			"${AUTOTEST_ROOT}/scripts/${SCRIPT}"
			RET=$?
			if [ $RET -ne 0 ]; then
				echo "${TS} ${SCRIPT} FAILED" >> "${AUTOTEST_ROOT}/logs/pu.db"
			else
				echo "${TS} ${SCRIPT} SUCCEEDED" >> "${AUTOTEST_ROOT}/logs/pu.db"
			fi
		) 2>&1 | timestamplog | tee "$OUTPUT" > "$REDIR"
		shift
	done
}

if [ "$1" = "--install-control" ]; then
	install_control
	shift
fi

if [ $# -gt 0 ]; then
	autotest_run $@
else
	autotest_run $AUTOTEST_RUN
fi
