#!/bin/bash

set -e

AUTOTEST_ROOT=/var/www/autotest

DB_FILE="${AUTOTEST_ROOT}/check-update.db"

LAST_MODIFIED=$(wget -q -S -O - http://eec.corp.anakeen.com/anakeen/repo/integration/3.2/webinst/content.xml 2>&1 | sed -n -e 's/^ *Last-Modified: \(.*\)$/\1/p' | head -1)

PREV_LAST_MODIFIED=""
if [ -f "${DB_FILE}" ]; then
	PREV_LAST_MODIFIED=$(head -1 "${DB_FILE}")
fi

if [ "${LAST_MODIFIED}" = "${PREV_LAST_MODIFIED}" ]; then
	exit 0
fi

echo "${LAST_MODIFIED}" > "${DB_FILE}"
"${AUTOTEST_ROOT}/autotest"
