#!/bin/bash

SETUID=33
AUTOTEST_RUN="3.2+pg91 3.2+pg84"
AUTOTEST_ROOT=/var/www/autotest
AUTOTEST_ADDON_INSTALL=""

if [ "$(id -u)" != "${SETUID}" ]; then
	printf "Script must be run under UID '%s'.\n" "${SETUID}"
	exit 1
fi

export AUTOTEST_ROOT
export AUTOTEST_ADDON_INSTALL

echo $$ >> "${AUTOTEST_ROOT}/run.lock"
LOCK_PID=$(head -1 "${AUTOTEST_ROOT}/run.lock")
if [ "${LOCK_PID}" != "$$" ]; then
	printf "Process already running with PID '%s'.\n" "${LOCK_PID}"
	exit 2
fi

function timestamplog {
	perl -MPOSIX -ne 'BEGIN{select STDOUT;$|=1;$ts=time()}printf("%s +%s %s",strftime("%Y-%m-%dT%H:%M:%S",localtime()),time()-$ts,$_);'
}

for RUNID in $AUTOTEST_RUN; do
	TS=$(date +%Y-%m-%dT%H:%M:%S)
	OUTPUT="${AUTOTEST_ROOT}/run_${RUNID}_${TS}.log"

	(
		"${AUTOTEST_ROOT}/run_${RUNID}"
		RET=$?
		if [ $RET -ne 0 ]; then
			echo "${TS} ${RUNID} FAILED" >> "${AUTOTEST_ROOT}/pu.db"
		else
			echo "${TS} ${RUNID} SUCCEEDED" >> "${AUTOTEST_ROOT}/pu.db"
		fi
	) 2>&1 | timestamplog > "$OUTPUT"
done
rm "${AUTOTEST_ROOT}/run.lock"
