#!/bin/bash

function php_version {
	php -r "print(preg_replace('/^(\d+\.\d+).*$/', '\1', PHP_VERSION));"
}

function get_php_ini_dcp_31 {
	PHP_VERSION=$(PHP_INI="" php_version)
	if [ "$PHP_VERSION" = "5.3" ]; then
		echo "$AUTOTEST_ROOT/scripts/dcp_31_php_53.ini"
	fi
	if [ "$PHP_VERSION" = "5.4" ]; then
		echo "$AUTOTEST_ROOT/scripts/dcp_31_php_54.ini"
	fi
}

function get_php_ini_dcp_32 {
	PHP_VERSION=$(PHP_INI="" php_version)
	if [ "$PHP_VERSION" = "5.3" ]; then
		echo "$AUTOTEST_ROOT/scripts/dcp_32_php_53.ini"
	fi
	if [ "$PHP_VERSION" = "5.4" ]; then
		echo "$AUTOTEST_ROOT/scripts/dcp_32_php_54.ini"
	fi
}

function set_php_ini_dcp_31 {
	export PHP_INI=""
	PHP_INI=$(get_php_ini_dcp_31)
	export PHP_INI
}

function set_php_ini_dcp_32 {
	export PHP_INI=""
	PHP_INI=$(get_php_ini_dcp_32)
	export PHP_INI
}

function filterout_crontab {
	crontab -l \
	| perl -ne '
		BEGIN { $in = "" }
		if (m/^# (BEGIN|END):(.*)$/) {
			if ($1 eq "BEGIN") { $in = $2 }
			elsif ($1 eq "END" && $2 eq $in) { $in = "" }
		} else {
			print if($in eq "")
		}
	' \
	| crontab -
}

function final_32 {
	(echo "<?php"; php-ini-set "$(get_php_ini_dcp_32)") > "${AUTOTEST_ROOT}/contexts/${CONTEXT_NAME}/config/local-dbaccess.php"
	"${AUTOTEST_ROOT}/dynacase-control/wiff" context "${CONTEXT_NAME}" exec ./wsh.php --api=set_param --appname=CORE --param=CORE_CLIENT --value="${CONTEXT_NAME}@$(hostname)"
}
